/**
 * AuraFlow — Theme token definitions and the complete theme registry.
 */

import type { ThemeId, ThemeDefinition, TypeScaleEntry } from "./types"

// --------- Shared primitives ---------

const fonts = {
  sans: `"Inter", ui-sans-serif, system-ui, sans-serif`,
  mono: `"Roboto Mono", ui-monospace, SFMono-Regular, Menlo, monospace`,
  grotesk: `"Space Grotesk", "Inter", sans-serif`,
  mochiy: `"Mochiy Pop One", "Inter", sans-serif`,
  playfair: `"Playfair Display", Georgia, serif`,
  cormorant: `"Cormorant Garamond", Georgia, serif`,
  outfit: `"Outfit", "Inter", sans-serif`,
  sora: `"Sora", "Inter", sans-serif`,
  dmSans: `"DM Sans", "Inter", sans-serif`,
  // We don't load these, we list them by name so the downloaded CSS
  // references real fonts users can swap out.
  serif: `"Cormorant Garamond", "Playfair Display", Georgia, serif`,
  slab: `"Roboto Mono", ui-monospace, monospace`,
}

// Helper — build a default type scale from a display + body + mono font.
function defaultTypeScale(opts: {
  display: string
  body: string
  mono: string
  displayWeight?: number
  bodyWeight?: number
}): TypeScaleEntry[] {
  const dw = opts.displayWeight ?? 900
  const bw = opts.bodyWeight ?? 400
  return [
    {
      name: "Display",
      description: "Bold, impactful headings for maximum visual impact.",
      sample: "Display",
      font: opts.display,
      weight: dw,
      size: "4.5rem",
      lineHeight: "1",
      tracking: "-0.02em",
      color: "primary",
    },
    {
      name: "Heading",
      description: "Section headers with distinctive character.",
      sample: "Heading",
      font: opts.display,
      weight: 700,
      size: "2rem",
      lineHeight: "1.15",
      tracking: "-0.01em",
      color: "primary",
    },
    {
      name: "Body",
      description: "Clean, readable text for content.",
      sample: "The path to enlightenment is paved with bold design choices.",
      font: opts.body,
      weight: bw,
      size: "1rem",
      lineHeight: "1.6",
      tracking: "0.01em",
      color: "text",
    },
    {
      name: "Mono",
      description: "Monospaced text for code and metadata.",
      sample: 'const theme = "auraflow"',
      font: opts.mono,
      weight: 500,
      size: "0.875rem",
      lineHeight: "1.5",
      tracking: "0",
      color: "textMuted",
    },
  ]
}

// --------- Theme definitions ---------

export const themes: Record<ThemeId, ThemeDefinition> = {
  light: {
    id: "light",
    name: "Cloud Light",
    tagline: "Soft, cute, daylight-friendly",
    description:
      "A playful pastel theme built around a rounded, approachable personality. Cloud Light leans into soft peach and periwinkle tones with a handwritten display face.",
    designer: "Dehlya Studio",
    year: "2024",
    mode: "light",
    inspiration: "Japanese cloud workbooks, Mochiy Pop display type, pastel iconography.",
    features: [
      "Generous rounded corners (2rem+)",
      "Pastel periwinkle and peach palette",
      "Handwritten Mochiy Pop display face",
      "Soft surface shadows, no hard borders",
    ],
    useCases: ["Personal sites", "Creative portfolios", "Friendly SaaS landing pages"],
    tokens: {
      background: "#F9F9F9",
      surface: "#FFFFFF",
      surfaceAlt: "#EEF1FA",
      border: "#E0E6F3",
      text: "#5C5C7B",
      textMuted: "#8C8CA8",
      textInverse: "#FFFFFF",
      primary: "#9FAAD2",
      primaryContrast: "#FFFFFF",
      secondary: "#E8A990",
      accent: "#E5EADF",
      success: "#7FB88F",
      warning: "#E8B274",
      danger: "#D98695",
      radius: "0.75rem",
      radiusLg: "1.75rem",
      shadow: "0 4px 20px -8px rgba(92, 92, 123, 0.15)",
      shadowLg: "0 20px 60px -20px rgba(92, 92, 123, 0.25)",
      fontSans: fonts.sans,
      fontDisplay: fonts.mochiy,
      fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #E8A990 0%, #9FAAD2 50%, #E5EADF 100%)",
      pattern:
        "radial-gradient(#e8a990 1px, transparent 1px), radial-gradient(#9faad2 1px, transparent 1px)",
    },
    typeScale: defaultTypeScale({ display: fonts.mochiy, body: fonts.sans, mono: fonts.mono }),
    motif: "\u3075\u308f\u3075\u308f",
    preview: ["#E8A990", "#9FAAD2", "#E5EADF"],
  },

  hanami: {
    id: "hanami",
    name: "Hanami",
    tagline: "Cherry blossoms at dusk",
    description:
      "The home theme of Dehlya Studio. Warm sakura pinks, elegant Playfair serifs, and the feeling of sitting under cherry blossom trees in spring. Refined, editorial, and unmistakably Japanese-inspired.",
    designer: "Dehlya Studio",
    year: "2026",
    mode: "light",
    inspiration: "Hanami festivals, sakura petals, Japanese typography, editorial serifs, warm spring evenings.",
    features: [
      "Playfair Display editorial serif",
      "Warm sakura pink palette",
      "Soft drop shadows",
      "Cherry blossom cloud pattern",
    ],
    useCases: ["Creative portfolios", "Personal sites", "Design studios", "Editorial blogs"],
    tokens: {
      background: "#FFF7F9",
      surface: "#FFFFFF",
      surfaceAlt: "#FFF2F5",
      border: "#F0D0D8",
      text: "#4A3040",
      textMuted: "#8A6878",
      textInverse: "#FFFFFF",
      primary: "#C8758B",
      primaryContrast: "#FFFFFF",
      secondary: "#C4A0C8",
      accent: "#E8A8B8",
      success: "#88C8A0",
      warning: "#E8C088",
      danger: "#D06070",
      radius: "1rem",
      radiusLg: "1.5rem",
      shadow: "0 4px 24px -8px rgba(212, 120, 138, 0.18)",
      shadowLg: "0 20px 60px -15px rgba(212, 120, 138, 0.22)",
      fontSans: fonts.dmSans,
      fontDisplay: fonts.sora,
      fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #D4788A 0%, #C4A0C8 50%, #E8B0A0 100%)",
      pattern:
        "radial-gradient(rgba(212, 120, 138, 0.06) 1px, transparent 1px), radial-gradient(rgba(196, 160, 200, 0.04) 1px, transparent 1px)",
    },
    typeScale: defaultTypeScale({ display: fonts.sora, body: fonts.dmSans, mono: fonts.mono }),
    motif: "\u82b1\u898b",
    preview: ["#D4788A", "#C4A0C8", "#E8B0A0"],
  },

  dark: {
    id: "dark",
    name: "Grid Dark",
    tagline: "Cyberpunk studio floor",
    description:
      "A hot-pink cyberpunk counterpart to Cloud Light. Grid Dark leans into neon primaries, sharp geometry, and a tech-grotesk display treatment.",
    designer: "Dehlya Studio",
    year: "2024",
    mode: "dark",
    inspiration: "90s hacker terminals, Tokyo neon signage, tactical HUDs.",
    features: [
      "Hot pink on near-black",
      "Sharp grid backgrounds",
      "Space Grotesk display",
      "Luminous border glow",
    ],
    useCases: ["Developer portfolios", "Music players", "Hacker tool landing pages"],
    tokens: {
      background: "#080808",
      surface: "#111111",
      surfaceAlt: "#1A1A1A",
      border: "#3D1A2E",
      text: "#F0F0F0",
      textMuted: "#909098",
      textInverse: "#080808",
      primary: "#FF69B4",
      primaryContrast: "#080808",
      secondary: "#8F9CFF",
      accent: "#FF69B4",
      success: "#7FE8A3",
      warning: "#FFD966",
      danger: "#FF6B6B",
      radius: "0.25rem",
      radiusLg: "0.5rem",
      shadow:
        "0 0 0 1px rgba(255, 105, 180, 0.15), 0 10px 40px -10px rgba(255, 105, 180, 0.15)",
      shadowLg:
        "0 0 0 1px rgba(255, 105, 180, 0.3), 0 30px 80px -20px rgba(255, 105, 180, 0.25)",
      fontSans: fonts.dmSans,
      fontDisplay: fonts.sora,
      fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #FF69B4 0%, #8F9CFF 50%, #080808 100%)",
      pattern:
        "linear-gradient(to right, rgba(255,105,180,0.1) 1px, transparent 1px), linear-gradient(to bottom, rgba(255,105,180,0.1) 1px, transparent 1px)",
    },
    typeScale: defaultTypeScale({ display: fonts.sora, body: fonts.dmSans, mono: fonts.mono }),
    motif: "DEHLYA.STUDIO",
    preview: ["#FF8FAB", "#8F9CFF", "#0A0A0A"],
  },

  atelier: {
    id: "atelier",
    name: "Atelier",
    tagline: "Editorial ivory, considered ink",
    description:
      "A serious, curator's-catalogue theme built for the /pro route. Warm ivory paper, deep forest-ink primary, and a bronze secondary. Serifed display, tight editorial rhythm, and paper-like surfaces \u2014 everything a recruiter sees says 'grown-up portfolio'.",
    designer: "Dehlya Studio",
    year: "2026",
    mode: "light",
    inspiration:
      "Swiss design journals, museum exhibition catalogues, fine-press editorial spreads, Kinfolk layouts.",
    features: [
      "Warm ivory paper background",
      "Deep forest-ink primary",
      "Warm bronze + sage accents",
      "Serif display with tight tracking",
      "Near-square corners for editorial rhythm",
    ],
    useCases: ["Resumes and CVs", "Editorial portfolios", "Professional hire-me pages"],
    tokens: {
      background: "#F4EFE6",
      surface: "#FFFBF2",
      surfaceAlt: "#EAE3D3",
      border: "#CEC2A4",
      text: "#1F1B15",
      textMuted: "#6B6357",
      textInverse: "#FFFBF2",
      primary: "#2A4A3E",
      primaryContrast: "#FFFBF2",
      secondary: "#8B6F47",
      accent: "#C9A96E",
      success: "#6B8E5A",
      warning: "#C9A96E",
      danger: "#9B3C3C",
      radius: "0.25rem",
      radiusLg: "0.5rem",
      shadow: "0 2px 16px -6px rgba(31, 27, 21, 0.12)",
      shadowLg: "0 20px 50px -18px rgba(31, 27, 21, 0.22)",
      fontSans: fonts.sans,
      fontDisplay: fonts.serif,
      fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #2A4A3E 0%, #C9A96E 100%)",
      pattern:
        "radial-gradient(rgba(31,27,21,0.08) 1px, transparent 1px), radial-gradient(rgba(201,169,110,0.08) 1px, transparent 1px)",
    },
    typeScale: defaultTypeScale({
      display: fonts.serif,
      body: fonts.sans,
      mono: fonts.mono,
      displayWeight: 600,
    }),
    motif: "\u2014 DH, Sion, CH \u2014",
    preview: ["#2A4A3E", "#C9A96E", "#F4EFE6"],
  },

  azuki: {
    id: "azuki",
    name: "Azuki",
    tagline: "Bold Japanese-inspired cyber manga",
    description:
      "Dark, loud, confrontational \u2014 Azuki leans into black canvas and vermilion red, all typeset in monospace to evoke the grid of a manga page printed on a terminal. Vertical Japanese katakana runs down the margins like a tank\u014dbon spine.",
    designer: "Dehlya Studio",
    year: "2024",
    mode: "dark",
    inspiration:
      "Japanese manga covers, anime title cards, Tokyo neon, terminal typography.",
    features: [
      "Bold red-on-black color scheme",
      "Monospace everywhere for grid rhythm",
      "Vertical Japanese katakana motif",
      "Asymmetric, dramatic composition",
      "Zero rounding \u2014 sharp slab edges",
    ],
    useCases: [
      "Anime / manga fan sites",
      "Japanese-inspired brands",
      "Gaming platforms",
      "Bold editorial designs",
      "Youth-oriented products",
    ],
    tokens: {
      background: "#0A0A0A",
      surface: "#151515",
      surfaceAlt: "#1C1C1C",
      border: "#2A2A2A",
      text: "#F4F4F4",
      textMuted: "#8A8A8A",
      textInverse: "#0A0A0A",
      primary: "#D93636",
      primaryContrast: "#0A0A0A",
      secondary: "#FF4D4D",
      accent: "#FF4D4D",
      success: "#7FE095",
      warning: "#E8A33D",
      danger: "#FF3B3B",
      radius: "0.125rem",
      radiusLg: "0.25rem",
      shadow: "0 0 0 1px rgba(217, 54, 54, 0.35)",
      shadowLg:
        "0 0 0 1px rgba(217, 54, 54, 0.5), 0 30px 80px -20px rgba(217, 54, 54, 0.25)",
      fontSans: fonts.mono,
      fontDisplay: fonts.mono,
      fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #D93636 0%, #0A0A0A 100%)",
      pattern:
        "repeating-linear-gradient(0deg, rgba(217,54,54,0.06) 0 1px, transparent 1px 6px)",
    },
    typeScale: [
      {
        name: "Display",
        description: "Bold, impactful headings for maximum visual impact.",
        sample: "AZUKI",
        font: fonts.mono,
        weight: 900,
        size: "6rem",
        lineHeight: "1",
        tracking: "-0.04em",
        color: "primary",
      },
      {
        name: "Heading",
        description: "Strong section headers with distinctive character.",
        sample: "\u30b7\u30b9\u30bf\u30fc\u30ba",
        font: fonts.mono,
        weight: 700,
        size: "2rem",
        lineHeight: "1.2",
        tracking: "0.01em",
        color: "primary",
      },
      {
        name: "Body",
        description: "Clean, readable monospace text for content.",
        sample: "The path to enlightenment is paved with bold design choices.",
        font: fonts.mono,
        weight: 400,
        size: "0.9375rem",
        lineHeight: "1.6",
        tracking: "0.03em",
        color: "text",
      },
      {
        name: "Label",
        description: "Uppercase metadata, tags and system labels.",
        sample: "BACK TO HOME",
        font: fonts.mono,
        weight: 600,
        size: "0.75rem",
        lineHeight: "1",
        tracking: "0.15em",
        color: "textMuted",
      },
    ],
    motif: "\u30b7\u30b9\u30bf\u30fc\u30ba\u30fb\u30b7\u30e3\u30aa",
    preview: ["#D93636", "#0A0A0A", "#F4F4F4"],
  },

  dazed: {
    id: "dazed",
    name: "Dazed",
    tagline: "Fashion-mag gradient dream",
    description:
      "A fashion-editorial theme with tilted display type, bold gradient washes, and oversized magazine-cover layouts.",
    designer: "Dehlya Studio",
    year: "2024",
    mode: "light",
    inspiration: "Dazed & Confused magazine, Y2K editorial, holographic foil.",
    features: [
      "Iridescent gradient backgrounds",
      "Extended condensed display type",
      "High contrast headlines",
      "Layered stickers and rotation",
    ],
    useCases: ["Magazine layouts", "Fashion lookbooks", "Creative agency sites"],
    tokens: {
      background: "#FDF7FA",
      surface: "#FFFFFF",
      surfaceAlt: "#FCE4EC",
      border: "#1A1A1A",
      text: "#1A1A1A",
      textMuted: "#6B6B6B",
      textInverse: "#FFFFFF",
      primary: "#FF3366",
      primaryContrast: "#FFFFFF",
      secondary: "#7C4DFF",
      accent: "#00E5B0",
      success: "#00C896",
      warning: "#FFB400",
      danger: "#FF3366",
      radius: "0rem",
      radiusLg: "0.25rem",
      shadow: "6px 6px 0 0 #1A1A1A",
      shadowLg: "12px 12px 0 0 #1A1A1A",
      fontSans: fonts.sans,
      fontDisplay: fonts.grotesk,
      fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #FF3366 0%, #7C4DFF 50%, #00E5B0 100%)",
      pattern:
        "radial-gradient(circle at 20% 30%, rgba(255,51,102,0.15), transparent 50%), radial-gradient(circle at 80% 70%, rgba(124,77,255,0.15), transparent 50%)",
    },
    typeScale: defaultTypeScale({ display: fonts.grotesk, body: fonts.sans, mono: fonts.mono }),
    motif: "DAZED \u2726 & \u2726 CONFUSED",
    preview: ["#FF3366", "#7C4DFF", "#00E5B0"],
  },

  carbon: {
    id: "carbon",
    name: "Carbon",
    tagline: "Industrial matte brutalism",
    description:
      "A stark industrial theme built on carbon black, concrete grey, and machine-orange accents. Utilitarian and direct.",
    designer: "Dehlya Studio",
    year: "2024",
    mode: "dark",
    inspiration: "Brutalist architecture, industrial signage, spec sheets.",
    features: [
      "Flat slab surfaces",
      "Hard edges, zero radius",
      "Monospaced data labels",
      "Single orange spot color",
    ],
    useCases: ["Developer tools", "SaaS dashboards", "Engineering sites"],
    tokens: {
      background: "#0E0E0E",
      surface: "#161616",
      surfaceAlt: "#222222",
      border: "#2E2E2E",
      text: "#E8E8E8",
      textMuted: "#9A9A9A",
      textInverse: "#0E0E0E",
      primary: "#FF6A00",
      primaryContrast: "#0E0E0E",
      secondary: "#5A5A5A",
      accent: "#C4C4C4",
      success: "#6FCF97",
      warning: "#FFB400",
      danger: "#EB5757",
      radius: "0rem",
      radiusLg: "0.125rem",
      shadow: "0 0 0 1px #2E2E2E",
      shadowLg: "0 0 0 1px #FF6A00, 0 12px 40px rgba(255,106,0,0.15)",
      fontSans: fonts.sans,
      fontDisplay: fonts.grotesk,
      fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #FF6A00 0%, #0E0E0E 100%)",
      pattern:
        "repeating-linear-gradient(90deg, rgba(255,255,255,0.02) 0 1px, transparent 1px 40px), repeating-linear-gradient(0deg, rgba(255,255,255,0.02) 0 1px, transparent 1px 40px)",
    },
    typeScale: defaultTypeScale({ display: fonts.grotesk, body: fonts.sans, mono: fonts.mono }),
    motif: "SPEC // CARBON.0",
    preview: ["#FF6A00", "#0E0E0E", "#2E2E2E"],
  },

  mintmarble: {
    id: "mintmarble",
    name: "Mint Marble",
    tagline: "Cool veined luxury",
    description:
      "A cool, luxurious theme with marble veining, mint primaries, and deep navy text. Feels like a high-end spa brand.",
    designer: "Dehlya Studio",
    year: "2024",
    mode: "light",
    inspiration: "Italian marble, cold-pressed beauty brands, art deco hotels.",
    features: [
      "Marble-veined surfaces",
      "Deep navy typography",
      "Soft mint primary",
      "Gold secondary accents",
    ],
    useCases: ["Luxury brands", "Spa & wellness", "Editorial magazines"],
    tokens: {
      background: "#F0F5F2",
      surface: "#FFFFFF",
      surfaceAlt: "#E1ECE6",
      border: "#CFDDD5",
      text: "#1C2A33",
      textMuted: "#5A6D78",
      textInverse: "#FFFFFF",
      primary: "#6FC3A3",
      primaryContrast: "#1C2A33",
      secondary: "#C9A96E",
      accent: "#AEDCC8",
      success: "#6FC3A3",
      warning: "#C9A96E",
      danger: "#C96E6E",
      radius: "0.5rem",
      radiusLg: "1.25rem",
      shadow: "0 8px 32px -12px rgba(28,42,51,0.15)",
      shadowLg: "0 24px 60px -20px rgba(28,42,51,0.2)",
      fontSans: fonts.sans,
      fontDisplay: fonts.grotesk,
      fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #6FC3A3 0%, #C9A96E 100%)",
      pattern:
        "radial-gradient(ellipse at 30% 20%, rgba(111,195,163,0.15), transparent 40%), radial-gradient(ellipse at 70% 80%, rgba(201,169,110,0.12), transparent 40%)",
    },
    typeScale: defaultTypeScale({ display: fonts.grotesk, body: fonts.sans, mono: fonts.mono }),
    motif: "Mint \u00b7 Marble \u00b7 Mmmh",
    preview: ["#6FC3A3", "#C9A96E", "#1C2A33"],
  },

  russian: {
    id: "russian",
    name: "Russian Constructivist",
    tagline: "Revolution red & black",
    description:
      "A constructivist theme with diagonal geometric composition, heavy slab display, and revolutionary red-and-black.",
    designer: "Dehlya Studio",
    year: "2024",
    mode: "light",
    inspiration: "El Lissitzky, Rodchenko posters, Soviet print design.",
    features: [
      "Diagonal geometric accents",
      "Heavy slab display",
      "Red / black / cream palette",
      "Strict uppercase typography",
    ],
    useCases: ["Bold launches", "Political art", "Editorial spreads"],
    tokens: {
      background: "#F2E8D5",
      surface: "#FFFFFF",
      surfaceAlt: "#E6D9BD",
      border: "#1A1A1A",
      text: "#1A1A1A",
      textMuted: "#4A4A4A",
      textInverse: "#F2E8D5",
      primary: "#C8102E",
      primaryContrast: "#F2E8D5",
      secondary: "#1A1A1A",
      accent: "#F2E8D5",
      success: "#4A7C40",
      warning: "#E0A800",
      danger: "#C8102E",
      radius: "0rem",
      radiusLg: "0rem",
      shadow: "6px 6px 0 0 #1A1A1A",
      shadowLg: "12px 12px 0 0 #1A1A1A",
      fontSans: fonts.sans,
      fontDisplay: fonts.grotesk,
      fontMono: fonts.mono,
      gradient:
        "linear-gradient(135deg, #C8102E 0%, #C8102E 50%, #1A1A1A 50%, #1A1A1A 100%)",
      pattern:
        "repeating-linear-gradient(-45deg, rgba(26,26,26,0.05) 0 8px, transparent 8px 24px)",
    },
    typeScale: defaultTypeScale({ display: fonts.grotesk, body: fonts.sans, mono: fonts.mono }),
    motif: "\u0420\u0415\u0412\u041e\u041b\u042e\u0426\u0418\u042f",
    preview: ["#C8102E", "#1A1A1A", "#F2E8D5"],
  },

  ceramic: {
    id: "ceramic",
    name: "Ceramic",
    tagline: "Handmade clay & cream",
    description:
      "Warm, handmade, crafted. Ceramic is built around terracotta, clay, and cream \u2014 like a potter's studio in print.",
    designer: "Dehlya Studio",
    year: "2024",
    mode: "light",
    inspiration: "Wabi-sabi pottery, hand-thrown clay, Morandi still life.",
    features: [
      "Warm terracotta primary",
      "Cream textured surfaces",
      "Soft ink text",
      "Hand-drawn dividers",
    ],
    useCases: ["Artisan brands", "Food blogs", "Craft portfolios"],
    tokens: {
      background: "#F5EEE3",
      surface: "#FBF6EC",
      surfaceAlt: "#EADFCE",
      border: "#D9C8B2",
      text: "#3A2A1F",
      textMuted: "#7A6B5C",
      textInverse: "#FBF6EC",
      primary: "#C86B4D",
      primaryContrast: "#FBF6EC",
      secondary: "#8F7A5C",
      accent: "#E3C29A",
      success: "#8FA36E",
      warning: "#D4A04C",
      danger: "#B54A3A",
      radius: "1rem",
      radiusLg: "2rem",
      shadow: "0 6px 24px -10px rgba(58,42,31,0.2)",
      shadowLg: "0 20px 60px -20px rgba(58,42,31,0.25)",
      fontSans: fonts.sans,
      fontDisplay: fonts.serif,
      fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #C86B4D 0%, #E3C29A 100%)",
      pattern:
        "radial-gradient(circle at 25% 25%, rgba(200,107,77,0.08), transparent 40%), radial-gradient(circle at 75% 75%, rgba(143,122,92,0.08), transparent 40%)",
    },
    typeScale: defaultTypeScale({ display: fonts.serif, body: fonts.sans, mono: fonts.mono }),
    motif: "~ earthenware ~",
    preview: ["#C86B4D", "#E3C29A", "#3A2A1F"],
  },

  soulwaves: {
    id: "soulwaves",
    name: "Soul Waves",
    tagline: "Late-night lofi radio",
    description:
      "A moody midnight theme with violet and teal waves, soft glow, and a radio-tuner feel. Perfect for music sites.",
    designer: "Dehlya Studio",
    year: "2024",
    mode: "dark",
    inspiration: "Lofi beats covers, synthwave album art, 2am playlists.",
    features: [
      "Violet + teal gradient",
      "Soft glowing surfaces",
      "Oversized serif display",
      "Vinyl / wave motifs",
    ],
    useCases: ["Music players", "Podcast sites", "Creative portfolios"],
    tokens: {
      background: "#0E0B1E",
      surface: "#17132E",
      surfaceAlt: "#221B45",
      border: "#2E2656",
      text: "#F0EBFF",
      textMuted: "#A095C8",
      textInverse: "#0E0B1E",
      primary: "#A78BFA",
      primaryContrast: "#0E0B1E",
      secondary: "#38BDF8",
      accent: "#F472B6",
      success: "#4ADE80",
      warning: "#FACC15",
      danger: "#FB7185",
      radius: "1rem",
      radiusLg: "2rem",
      shadow: "0 0 40px -10px rgba(167,139,250,0.35)",
      shadowLg: "0 0 80px -20px rgba(167,139,250,0.5)",
      fontSans: fonts.sans,
      fontDisplay: fonts.grotesk,
      fontMono: fonts.mono,
      gradient:
        "linear-gradient(135deg, #A78BFA 0%, #38BDF8 50%, #F472B6 100%)",
      pattern:
        "radial-gradient(ellipse at 20% 30%, rgba(167,139,250,0.25), transparent 50%), radial-gradient(ellipse at 80% 70%, rgba(56,189,248,0.2), transparent 50%)",
    },
    typeScale: defaultTypeScale({ display: fonts.grotesk, body: fonts.sans, mono: fonts.mono }),
    motif: "\u2727 2am playlist \u2727",
    preview: ["#A78BFA", "#38BDF8", "#0E0B1E"],
  },

  redmaiden: {
    id: "redmaiden",
    name: "Red Maiden",
    tagline: "Gothic romance in scarlet",
    description:
      "A gothic romance theme \u2014 deep burgundy, ivory parchment, and blackletter display. Like a love letter from a haunted library.",
    designer: "Dehlya Studio",
    year: "2024",
    mode: "dark",
    inspiration: "Victorian novels, gothic romance, oxblood velvet.",
    features: [
      "Blackletter display type",
      "Parchment surfaces",
      "Deep burgundy primary",
      "Ornate divider flourishes",
    ],
    useCases: ["Fiction sites", "Literary magazines", "Moody portfolios"],
    tokens: {
      background: "#1C0B0F",
      surface: "#2B1016",
      surfaceAlt: "#3A141B",
      border: "#5A1F2A",
      text: "#F5E9DC",
      textMuted: "#C8A89A",
      textInverse: "#1C0B0F",
      primary: "#B8293A",
      primaryContrast: "#F5E9DC",
      secondary: "#8B1E2B",
      accent: "#D4A574",
      success: "#7A9E5B",
      warning: "#D4A574",
      danger: "#E63946",
      radius: "0.25rem",
      radiusLg: "0.5rem",
      shadow: "0 8px 40px -10px rgba(184,41,58,0.35)",
      shadowLg: "0 20px 60px -20px rgba(184,41,58,0.5)",
      fontSans: fonts.serif,
      fontDisplay: fonts.serif,
      fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #B8293A 0%, #1C0B0F 100%)",
      pattern:
        "radial-gradient(ellipse at 50% 0%, rgba(184,41,58,0.2), transparent 60%)",
    },
    typeScale: defaultTypeScale({
      display: fonts.serif,
      body: fonts.serif,
      mono: fonts.mono,
    }),
    motif: "\u2720 dearest reader \u2720",
    preview: ["#B8293A", "#D4A574", "#1C0B0F"],
  },

  y2k: {
    id: "y2k",
    name: "Y2K",
    tagline: "Chrome bubble optimism",
    description:
      "Pure year-2000 optimism \u2014 chrome gradients, bubble type, candy holographics, and cyber-blue accents.",
    designer: "Dehlya Studio",
    year: "2024",
    mode: "light",
    inspiration: "Motorola flip phones, MSN Messenger, iPod nano, frutiger aero.",
    features: [
      "Chrome gradient surfaces",
      "Bubble rounded display",
      "Holographic accents",
      "Gel button treatments",
    ],
    useCases: ["Playful brands", "Retro-futurist sites", "Gen Z audiences"],
    tokens: {
      background: "#E0F2FE",
      surface: "#FFFFFF",
      surfaceAlt: "#BAE6FD",
      border: "#93C5FD",
      text: "#0C4A6E",
      textMuted: "#3B82AD",
      textInverse: "#FFFFFF",
      primary: "#0EA5E9",
      primaryContrast: "#FFFFFF",
      secondary: "#C026D3",
      accent: "#F472B6",
      success: "#22D3EE",
      warning: "#FACC15",
      danger: "#EC4899",
      radius: "1.5rem",
      radiusLg: "2.5rem",
      shadow:
        "0 8px 32px -8px rgba(14,165,233,0.35), inset 0 1px 0 rgba(255,255,255,0.8)",
      shadowLg: "0 20px 60px -12px rgba(14,165,233,0.45)",
      fontSans: fonts.sans,
      fontDisplay: fonts.mochiy,
      fontMono: fonts.mono,
      gradient:
        "linear-gradient(135deg, #0EA5E9 0%, #C026D3 50%, #F472B6 100%)",
      pattern:
        "radial-gradient(circle at 20% 30%, rgba(14,165,233,0.25), transparent 40%), radial-gradient(circle at 80% 70%, rgba(192,38,211,0.2), transparent 40%)",
    },
    typeScale: defaultTypeScale({ display: fonts.mochiy, body: fonts.sans, mono: fonts.mono }),
    motif: "\u02cf\u02cb\u00b0\u2022*\u2040\u27b7 Y2K",
    preview: ["#0EA5E9", "#C026D3", "#F472B6"],
  },

  salome: {
    id: "salome",
    name: "Salom\u00e9",
    tagline: "Decadent art nouveau",
    description:
      "Fin-de-si\u00e8cle decadence \u2014 olive, gold, plum, and ivory. Serpentine curves and gold leaf flourishes.",
    designer: "Dehlya Studio",
    year: "2024",
    mode: "light",
    inspiration: "Aubrey Beardsley, Klimt, art nouveau posters.",
    features: [
      "Gold leaf primary",
      "Serpentine curves",
      "Olive and plum accents",
      "Ivory paper background",
    ],
    useCases: ["Luxury editorial", "Wine brands", "Theatre and opera"],
    tokens: {
      background: "#F5F1E8",
      surface: "#FFFBF0",
      surfaceAlt: "#EAE4D1",
      border: "#3E3520",
      text: "#3E3520",
      textMuted: "#6B5E40",
      textInverse: "#FFFBF0",
      primary: "#B8860B",
      primaryContrast: "#FFFBF0",
      secondary: "#5A3A5A",
      accent: "#8B956D",
      success: "#8B956D",
      warning: "#B8860B",
      danger: "#8B2E3C",
      radius: "0.5rem",
      radiusLg: "1rem",
      shadow: "0 8px 32px -12px rgba(62,53,32,0.25)",
      shadowLg: "0 24px 60px -20px rgba(62,53,32,0.35)",
      fontSans: fonts.serif,
      fontDisplay: fonts.serif,
      fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #B8860B 0%, #5A3A5A 100%)",
      pattern:
        "radial-gradient(circle at 50% 50%, rgba(184,134,11,0.1), transparent 50%)",
    },
    typeScale: defaultTypeScale({
      display: fonts.serif,
      body: fonts.serif,
      mono: fonts.mono,
    }),
    motif: "\u2767 Salom\u00e9 \u2767",
    preview: ["#B8860B", "#5A3A5A", "#8B956D"],
  },

  // ===============================================
  //  NEW BATCH — 12 themes for every kind of developer
  // ===============================================

  nord: {
    id: "nord",
    name: "Nord",
    tagline: "Arctic clarity, Scandinavian calm",
    description: "For the developer who keeps their desk empty, their code clean, and their apartment at exactly 21\u00b0C. Nord is cold blue precision with warm accents \u2014 hygge for your interface.",
    designer: "Dehlya Studio", year: "2026", mode: "dark",
    inspiration: "Nordic fjords, Dieter Rams, the color of ice at twilight, IKEA showrooms at closing time.",
    features: ["Cool blue-gray palette", "Warm accent pops", "Clean sans typography", "Generous whitespace"],
    useCases: ["Developer portfolios", "Documentation sites", "SaaS dashboards", "Technical blogs"],
    tokens: {
      background: "#2E3440", surface: "#3B4252", surfaceAlt: "#434C5E", border: "#4C566A",
      text: "#ECEFF4", textMuted: "#D8DEE9", textInverse: "#2E3440",
      primary: "#88C0D0", primaryContrast: "#2E3440", secondary: "#81A1C1", accent: "#EBCB8B",
      success: "#A3BE8C", warning: "#EBCB8B", danger: "#BF616A",
      radius: "0.5rem", radiusLg: "0.75rem",
      shadow: "0 4px 16px -4px rgba(0,0,0,0.4)", shadowLg: "0 16px 48px -12px rgba(0,0,0,0.5)",
      fontSans: fonts.sans, fontDisplay: fonts.grotesk, fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #88C0D0 0%, #81A1C1 50%, #5E81AC 100%)",
      pattern: "linear-gradient(to right, rgba(136,192,208,0.05) 1px, transparent 1px), linear-gradient(to bottom, rgba(136,192,208,0.05) 1px, transparent 1px)",
    },
    typeScale: defaultTypeScale({ display: fonts.grotesk, body: fonts.sans, mono: fonts.mono }),
    motif: "\u2744 Nord",
    preview: ["#88C0D0", "#81A1C1", "#2E3440"],
  },

  terminal: {
    id: "terminal",
    name: "Terminal",
    tagline: "Green phosphor on black. No GUI needed.",
    description: "For the developer who thinks browsers are bloated, GUIs are for beginners, and the most beautiful interface ever made was the VT100. Monospaced everything. Zero decoration.",
    designer: "Dehlya Studio", year: "2026", mode: "dark",
    inspiration: "VT100 terminals, The Matrix, 90s hacker movies, ssh into production at 3am.",
    features: ["Phosphor green on pure black", "100% monospaced", "No border radius anywhere", "Blinking cursor energy"],
    useCases: ["Hacker portfolios", "CLI tool landing pages", "Security blogs", "Retro tech sites"],
    tokens: {
      background: "#000000", surface: "#0a0a0a", surfaceAlt: "#111111", border: "#1a3a1a",
      text: "#33ff33", textMuted: "#22aa22", textInverse: "#000000",
      primary: "#33ff33", primaryContrast: "#000000", secondary: "#00cc66", accent: "#ffcc00",
      success: "#33ff33", warning: "#ffcc00", danger: "#ff3333",
      radius: "0rem", radiusLg: "0rem",
      shadow: "0 0 10px rgba(51,255,51,0.15)", shadowLg: "0 0 30px rgba(51,255,51,0.2)",
      fontSans: fonts.mono, fontDisplay: fonts.mono, fontMono: fonts.mono,
      gradient: "linear-gradient(180deg, #33ff33 0%, #000000 100%)",
      pattern: "repeating-linear-gradient(0deg, rgba(51,255,51,0.03) 0 1px, transparent 1px 3px)",
    },
    typeScale: defaultTypeScale({ display: fonts.mono, body: fonts.mono, mono: fonts.mono }),
    motif: "> Terminal_",
    preview: ["#33ff33", "#000000", "#00cc66"],
  },

  neobrutalist: {
    id: "neobrutalist",
    name: "Neobrutalist",
    tagline: "Thick borders. Bright colors. No apologies.",
    description: "For the indie maker who ships MVPs on Friday nights, charges $9 for an ebook, and thinks 'polished' is overrated. Chunky borders, system fonts, colors that slap.",
    designer: "Dehlya Studio", year: "2026", mode: "light",
    inspiration: "Gumroad, Notion circa 2020, Memphis design, punk zines, duct tape engineering.",
    features: ["4px black borders everywhere", "Offset drop shadows", "System stack fonts", "Eye-catching neon accents"],
    useCases: ["Indie product pages", "Personal blogs", "Newsletter landing pages", "Side project showcases"],
    tokens: {
      background: "#FEFBEC", surface: "#FFFFFF", surfaceAlt: "#FFF3C4", border: "#000000",
      text: "#000000", textMuted: "#444444", textInverse: "#FFFFFF",
      primary: "#FF5C5C", primaryContrast: "#000000", secondary: "#3B82F6", accent: "#FACC15",
      success: "#22C55E", warning: "#FACC15", danger: "#FF5C5C",
      radius: "0rem", radiusLg: "0.25rem",
      shadow: "4px 4px 0 0 #000000", shadowLg: "8px 8px 0 0 #000000",
      fontSans: `system-ui, -apple-system, sans-serif`, fontDisplay: `system-ui, -apple-system, sans-serif`, fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #FF5C5C 0%, #FACC15 50%, #3B82F6 100%)",
      pattern: "repeating-linear-gradient(45deg, rgba(0,0,0,0.02) 0 4px, transparent 4px 12px)",
    },
    typeScale: defaultTypeScale({ display: `system-ui, -apple-system, sans-serif`, body: `system-ui, -apple-system, sans-serif`, mono: fonts.mono, displayWeight: 800 }),
    motif: "[ BRUTAL ]",
    preview: ["#FF5C5C", "#FACC15", "#000000"],
  },

  cottagecore: {
    id: "cottagecore",
    name: "Cottagecore",
    tagline: "Sage, cream, and sourdough between deploys",
    description: "For the developer who codes from a countryside cottage, grows herbs on the windowsill, and believes software should feel as warm as fresh bread. Soft, natural, handmade.",
    designer: "Dehlya Studio", year: "2026", mode: "light",
    inspiration: "English country gardens, hand-thrown pottery, linen textures, Beatrix Potter illustrations.",
    features: ["Sage green + warm cream palette", "Rounded generous corners", "Soft organic shadows", "Warm serif display"],
    useCases: ["Food blogs", "Craft portfolios", "Wellness sites", "Artisan e-commerce"],
    tokens: {
      background: "#FAF5EE", surface: "#FFFFFF", surfaceAlt: "#F0EBE0", border: "#D4C8B0",
      text: "#3D3A34", textMuted: "#7A7468", textInverse: "#FFFFFF",
      primary: "#7A9E6D", primaryContrast: "#FFFFFF", secondary: "#B8956A", accent: "#D4A574",
      success: "#7A9E6D", warning: "#D4A574", danger: "#C27055",
      radius: "1rem", radiusLg: "2rem",
      shadow: "0 4px 20px -6px rgba(61,58,52,0.12)", shadowLg: "0 20px 50px -15px rgba(61,58,52,0.18)",
      fontSans: fonts.sans, fontDisplay: fonts.serif, fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #7A9E6D 0%, #D4A574 100%)",
      pattern: "radial-gradient(rgba(122,158,109,0.08) 1px, transparent 1px), radial-gradient(rgba(212,165,116,0.06) 1px, transparent 1px)",
    },
    typeScale: defaultTypeScale({ display: fonts.serif, body: fonts.sans, mono: fonts.mono, displayWeight: 600 }),
    motif: "\ud83c\udf3f Cottage",
    preview: ["#7A9E6D", "#D4A574", "#FAF5EE"],
  },

  cyberpulse: {
    id: "cyberpulse",
    name: "Cyberpulse",
    tagline: "Neon rain on dark chrome",
    description: "For the cybersecurity researcher walking through neon-lit Shinjuku at midnight, headphones on, packet sniffer running. Electric cyan and hot magenta on deep purple void.",
    designer: "Dehlya Studio", year: "2026", mode: "dark",
    inspiration: "Blade Runner, Ghost in the Shell, Tokyo neon signage, cybersec dashboards, rain on chrome.",
    features: ["Deep purple + electric neon", "Glowing borders", "Sharp angular design", "High-contrast readability"],
    useCases: ["Cybersecurity tools", "Gaming sites", "Tech conference sites", "Developer streams"],
    tokens: {
      background: "#0D0221", surface: "#150533", surfaceAlt: "#1A0844", border: "#2D1B69",
      text: "#E0D7FF", textMuted: "#A095CC", textInverse: "#0D0221",
      primary: "#00F0FF", primaryContrast: "#0D0221", secondary: "#FF00AA", accent: "#FFE600",
      success: "#00FF88", warning: "#FFE600", danger: "#FF0055",
      radius: "0.25rem", radiusLg: "0.5rem",
      shadow: "0 0 20px rgba(0,240,255,0.2), 0 0 0 1px rgba(0,240,255,0.15)", shadowLg: "0 0 50px rgba(0,240,255,0.3), 0 0 0 1px rgba(255,0,170,0.2)",
      fontSans: fonts.sans, fontDisplay: fonts.grotesk, fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #00F0FF 0%, #FF00AA 50%, #FFE600 100%)",
      pattern: "linear-gradient(to right, rgba(0,240,255,0.04) 1px, transparent 1px), linear-gradient(to bottom, rgba(255,0,170,0.03) 1px, transparent 1px)",
    },
    typeScale: defaultTypeScale({ display: fonts.grotesk, body: fonts.sans, mono: fonts.mono }),
    motif: "\u26a1 CYBER",
    preview: ["#00F0FF", "#FF00AA", "#0D0221"],
  },

  gazette: {
    id: "gazette",
    name: "Gazette",
    tagline: "All the news that's fit to render",
    description: "For the writer who wants their blog to feel like unfolding a broadsheet newspaper. Ink on paper, serif headlines, column layouts. Authority through typography.",
    designer: "Dehlya Studio", year: "2026", mode: "light",
    inspiration: "The New York Times, The Guardian, letterpress printing, newsroom typewriters, morning coffee rituals.",
    features: ["Pure black-on-white", "Serif headlines, sans body", "Hairline rules and column dividers", "Zero color distraction"],
    useCases: ["Writing blogs", "News sites", "Editorial magazines", "Long-form content"],
    tokens: {
      background: "#FAFAF8", surface: "#FFFFFF", surfaceAlt: "#F2F2F0", border: "#E0E0DE",
      text: "#1A1A1A", textMuted: "#666666", textInverse: "#FFFFFF",
      primary: "#1A1A1A", primaryContrast: "#FFFFFF", secondary: "#666666", accent: "#C8102E",
      success: "#2E7D32", warning: "#E65100", danger: "#C8102E",
      radius: "0rem", radiusLg: "0.125rem",
      shadow: "0 1px 3px rgba(0,0,0,0.08)", shadowLg: "0 4px 16px rgba(0,0,0,0.1)",
      fontSans: fonts.sans, fontDisplay: fonts.serif, fontMono: fonts.mono,
      gradient: "linear-gradient(180deg, #1A1A1A 0%, #FAFAF8 100%)",
      pattern: "repeating-linear-gradient(90deg, transparent 0, transparent 49.5%, rgba(0,0,0,0.06) 49.5%, rgba(0,0,0,0.06) 50.5%, transparent 50.5%)",
    },
    typeScale: defaultTypeScale({ display: fonts.serif, body: fonts.sans, mono: fonts.mono, displayWeight: 700 }),
    motif: "\u00a7 Gazette",
    preview: ["#1A1A1A", "#C8102E", "#FAFAF8"],
  },

  sakura: {
    id: "sakura",
    name: "Sakura",
    tagline: "Pastel petals on a spring breeze",
    description: "For the developer who decorates their IDE with pastel extensions, names variables in Japanese, and thinks every website should feel like a Studio Ghibli background. Soft lavender, cherry blossom pink, mint whispers.",
    designer: "Dehlya Studio", year: "2026", mode: "light",
    inspiration: "Cherry blossoms in Kyoto, matcha lattes, Studio Ghibli palettes, kawaii stationery, Animal Crossing.",
    features: ["Pastel pink + lavender palette", "Soft rounded everything", "Gentle gradient surfaces", "Dreamy, floaty feel"],
    useCases: ["Personal blogs", "Creative portfolios", "Social apps", "Lifestyle brands"],
    tokens: {
      background: "#FFF5F9", surface: "#FFFFFF", surfaceAlt: "#FFF0F5", border: "#F5D5E0",
      text: "#5C4055", textMuted: "#9A7A8A", textInverse: "#FFFFFF",
      primary: "#E891AA", primaryContrast: "#FFFFFF", secondary: "#B8A9E8", accent: "#88D8C0",
      success: "#88D8C0", warning: "#F5D080", danger: "#E87088",
      radius: "1.25rem", radiusLg: "2rem",
      shadow: "0 4px 20px -6px rgba(232,145,170,0.2)", shadowLg: "0 20px 60px -15px rgba(184,169,232,0.25)",
      fontSans: fonts.sans, fontDisplay: fonts.mochiy, fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #E891AA 0%, #B8A9E8 50%, #88D8C0 100%)",
      pattern: "radial-gradient(rgba(232,145,170,0.1) 1px, transparent 1px), radial-gradient(rgba(184,169,232,0.08) 1px, transparent 1px)",
    },
    typeScale: defaultTypeScale({ display: fonts.mochiy, body: fonts.sans, mono: fonts.mono }),
    motif: "\ud83c\udf38 \u685c",
    preview: ["#E891AA", "#B8A9E8", "#88D8C0"],
  },

  synthwave: {
    id: "synthwave",
    name: "Synthwave",
    tagline: "Sunset grids and chrome dreams",
    description: "For the developer who listens to Kavinsky while coding, has a mechanical keyboard with RGB, and misses an 80s they never actually lived. Retro sunset gradients, chrome accents, neon grid.",
    designer: "Dehlya Studio", year: "2026", mode: "dark",
    inspiration: "Outrun, Tron Legacy, 80s VHS covers, Miami Vice, DeLorean dashboards, pixel sunsets.",
    features: ["Purple-pink sunset gradient", "Chrome/silver accents", "Neon grid pattern", "Retro-futurist typography"],
    useCases: ["Music sites", "Gaming portfolios", "Retro-themed apps", "Developer streams"],
    tokens: {
      background: "#1A1025", surface: "#241535", surfaceAlt: "#2E1B45", border: "#4A2D70",
      text: "#F0E0FF", textMuted: "#B898D8", textInverse: "#1A1025",
      primary: "#FF6EC7", primaryContrast: "#1A1025", secondary: "#00D4FF", accent: "#FFD700",
      success: "#00FF9F", warning: "#FFD700", danger: "#FF3860",
      radius: "0.25rem", radiusLg: "0.5rem",
      shadow: "0 0 20px rgba(255,110,199,0.2)", shadowLg: "0 0 60px rgba(255,110,199,0.3), 0 0 30px rgba(0,212,255,0.15)",
      fontSans: fonts.sans, fontDisplay: fonts.grotesk, fontMono: fonts.mono,
      gradient: "linear-gradient(180deg, #FF6EC7 0%, #FF3860 30%, #4A2D70 70%, #1A1025 100%)",
      pattern: "linear-gradient(to right, rgba(255,110,199,0.06) 1px, transparent 1px), linear-gradient(to bottom, rgba(0,212,255,0.04) 1px, transparent 1px)",
    },
    typeScale: defaultTypeScale({ display: fonts.grotesk, body: fonts.sans, mono: fonts.mono }),
    motif: "\u2593 SYNTH",
    preview: ["#FF6EC7", "#00D4FF", "#1A1025"],
  },

  coastal: {
    id: "coastal",
    name: "Coastal",
    tagline: "Salt air and blue horizons",
    description: "For the remote worker coding from a beach house who couldn't care less about sprint velocity. Ocean blues, sandy warmth, coral accents \u2014 the sound of waves between keyboard clicks.",
    designer: "Dehlya Studio", year: "2026", mode: "light",
    inspiration: "Mediterranean coastlines, driftwood, sea glass, nautical charts, sunset surfing.",
    features: ["Ocean blue + sand palette", "Warm coral accents", "Breezy open layouts", "Natural, relaxed feel"],
    useCases: ["Travel blogs", "Hospitality sites", "Wellness apps", "Remote work tools"],
    tokens: {
      background: "#F8F6F0", surface: "#FFFFFF", surfaceAlt: "#EDF4F8", border: "#C8D8E4",
      text: "#2C3E50", textMuted: "#6B8BA4", textInverse: "#FFFFFF",
      primary: "#2B7A9E", primaryContrast: "#FFFFFF", secondary: "#E8A87C", accent: "#E76F51",
      success: "#5CB88A", warning: "#E8A87C", danger: "#E76F51",
      radius: "0.75rem", radiusLg: "1.5rem",
      shadow: "0 4px 20px -6px rgba(43,122,158,0.15)", shadowLg: "0 20px 60px -15px rgba(43,122,158,0.2)",
      fontSans: fonts.sans, fontDisplay: fonts.grotesk, fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #2B7A9E 0%, #5CB88A 50%, #E8A87C 100%)",
      pattern: "radial-gradient(rgba(43,122,158,0.06) 1px, transparent 1px)",
    },
    typeScale: defaultTypeScale({ display: fonts.grotesk, body: fonts.sans, mono: fonts.mono }),
    motif: "~ Coastal",
    preview: ["#2B7A9E", "#E8A87C", "#E76F51"],
  },

  mocha: {
    id: "mocha",
    name: "Mocha",
    tagline: "Warm espresso in a dark room",
    description: "For the coffee shop coder who hates blue light, loves warm tones, and thinks every dark theme should feel like a cozy evening, not a cold void. Espresso browns, cream highlights, cinnamon accents.",
    designer: "Dehlya Studio", year: "2026", mode: "dark",
    inspiration: "Catppuccin Mocha, late-night coffee shops, leather journals, warm desk lamps, Autumn evenings.",
    features: ["Warm brown dark palette", "Zero blue light", "Cream text on espresso", "Cozy, eye-friendly contrast"],
    useCases: ["Developer tools", "Reading apps", "Journaling sites", "Dark-mode-first products"],
    tokens: {
      background: "#1E1814", surface: "#2A221C", surfaceAlt: "#342C25", border: "#4A3E35",
      text: "#E8DDD0", textMuted: "#B8A898", textInverse: "#1E1814",
      primary: "#E8A87C", primaryContrast: "#1E1814", secondary: "#C8956A", accent: "#D4B48E",
      success: "#A8C878", warning: "#D4B48E", danger: "#D47070",
      radius: "0.5rem", radiusLg: "1rem",
      shadow: "0 4px 20px -6px rgba(0,0,0,0.5)", shadowLg: "0 20px 60px -15px rgba(0,0,0,0.6)",
      fontSans: fonts.sans, fontDisplay: fonts.grotesk, fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #E8A87C 0%, #C8956A 50%, #1E1814 100%)",
      pattern: "radial-gradient(rgba(232,168,124,0.04) 1px, transparent 1px)",
    },
    typeScale: defaultTypeScale({ display: fonts.grotesk, body: fonts.sans, mono: fonts.mono }),
    motif: "\u2615 Mocha",
    preview: ["#E8A87C", "#C8956A", "#1E1814"],
  },

  frosted: {
    id: "frosted",
    name: "Frosted",
    tagline: "Glass, blur, and light through ice",
    description: "For the Apple fan who believes every surface should be slightly transparent with a blur behind it. Glassmorphism done right \u2014 bright, clean, with depth you can almost touch.",
    designer: "Dehlya Studio", year: "2026", mode: "light",
    inspiration: "macOS Big Sur, frosted glass, ice crystals, Apple Keynote slides, morning dew.",
    features: ["Glassmorphism surfaces", "Cool blue-gray palette", "Soft multi-layer depth", "Ultra-clean typography"],
    useCases: ["SaaS products", "Apple-inspired portfolios", "Finance dashboards", "Design tool UIs"],
    tokens: {
      background: "#F2F5F8", surface: "#FFFFFF", surfaceAlt: "#E8ECF2", border: "#D0D8E0",
      text: "#1C2333", textMuted: "#6B7A8D", textInverse: "#FFFFFF",
      primary: "#007AFF", primaryContrast: "#FFFFFF", secondary: "#5856D6", accent: "#34C759",
      success: "#34C759", warning: "#FF9500", danger: "#FF3B30",
      radius: "0.75rem", radiusLg: "1.25rem",
      shadow: "0 4px 16px -4px rgba(0,0,0,0.08), 0 0 0 1px rgba(0,0,0,0.04)", shadowLg: "0 24px 48px -12px rgba(0,0,0,0.12)",
      fontSans: `-apple-system, BlinkMacSystemFont, "SF Pro", "Inter", sans-serif`, fontDisplay: `-apple-system, BlinkMacSystemFont, "SF Pro", "Inter", sans-serif`, fontMono: `"SF Mono", ${fonts.mono}`,
      gradient: "linear-gradient(135deg, #007AFF 0%, #5856D6 50%, #AF52DE 100%)",
      pattern: "radial-gradient(rgba(0,122,255,0.04) 1px, transparent 1px)",
    },
    typeScale: defaultTypeScale({ display: `-apple-system, BlinkMacSystemFont, "SF Pro", "Inter", sans-serif`, body: `-apple-system, BlinkMacSystemFont, "Inter", sans-serif`, mono: `"SF Mono", ${fonts.mono}` }),
    motif: "\u25c9 Frosted",
    preview: ["#007AFF", "#5856D6", "#F2F5F8"],
  },

  pop: {
    id: "pop",
    name: "Pop",
    tagline: "Every website should be a candy store",
    description: "For the creative agency designer who thinks 'professional' means 'boring'. Bright saturated colors, chunky rounded shapes, playful energy. Makes serious products feel fun.",
    designer: "Dehlya Studio", year: "2026", mode: "light",
    inspiration: "Figma's brand, Duolingo, LEGO, Andy Warhol, candy packaging, children's book illustrations.",
    features: ["Saturated candy colors", "Extra-rounded corners", "Playful chunky type", "High-energy gradients"],
    useCases: ["Creative agencies", "Kids' apps", "Playful brands", "Social platforms"],
    tokens: {
      background: "#FFFDF5", surface: "#FFFFFF", surfaceAlt: "#FFF5E6", border: "#FFE0B2",
      text: "#2D1B4E", textMuted: "#6B5A8A", textInverse: "#FFFFFF",
      primary: "#FF6B35", primaryContrast: "#FFFFFF", secondary: "#7B2DFF", accent: "#00C9A7",
      success: "#00C9A7", warning: "#FFBE0B", danger: "#FF006E",
      radius: "1.5rem", radiusLg: "2.5rem",
      shadow: "0 6px 24px -6px rgba(255,107,53,0.25)", shadowLg: "0 20px 60px -15px rgba(123,45,255,0.2)",
      fontSans: fonts.sans, fontDisplay: fonts.mochiy, fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #FF6B35 0%, #FF006E 33%, #7B2DFF 66%, #00C9A7 100%)",
      pattern: "radial-gradient(rgba(255,107,53,0.08) 2px, transparent 2px), radial-gradient(rgba(123,45,255,0.06) 2px, transparent 2px)",
    },
    typeScale: defaultTypeScale({ display: fonts.mochiy, body: fonts.sans, mono: fonts.mono }),
    motif: "\u2605 POP!",
    preview: ["#FF6B35", "#7B2DFF", "#00C9A7"],
  },

  // ===============================================
  //  BATCH 3 — cultures, places, sensory experiences
  // ===============================================

  souk: {
    id: "souk",
    name: "Souk",
    tagline: "Saffron, tiles, and spice-warm light",
    description: "For someone who dreams in Moroccan mosaics \u2014 warm saffron golds, deep ocean blues, and terracotta earth. Lantern light through carved metal. The organized chaos of a marketplace that's been there for centuries.",
    designer: "Dehlya Studio", year: "2026", mode: "light",
    inspiration: "Marrakech medinas, zellige tile patterns, turmeric markets, riad courtyards, brass lanterns.",
    features: ["Saffron gold + deep ocean blue", "Warm terracotta accents", "Ornate border details", "Lantern-warm lighting feel"],
    useCases: ["Travel blogs", "Restaurant sites", "Cultural magazines", "Artisan e-commerce"],
    tokens: {
      background: "#FDF6EC", surface: "#FFFFFF", surfaceAlt: "#F5EAD6", border: "#D4B888",
      text: "#2A1F14", textMuted: "#7A6A55", textInverse: "#FFFFFF",
      primary: "#1A5276", primaryContrast: "#FDF6EC", secondary: "#D4A03C", accent: "#C0653A",
      success: "#5A8A50", warning: "#D4A03C", danger: "#B83C3C",
      radius: "0.375rem", radiusLg: "0.75rem",
      shadow: "0 4px 18px -6px rgba(42,31,20,0.15)", shadowLg: "0 20px 50px -15px rgba(42,31,20,0.22)",
      fontSans: fonts.sans, fontDisplay: fonts.serif, fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #1A5276 0%, #D4A03C 50%, #C0653A 100%)",
      pattern: "radial-gradient(rgba(26,82,118,0.06) 1.5px, transparent 1.5px), radial-gradient(rgba(212,160,60,0.05) 1.5px, transparent 1.5px)",
    },
    typeScale: defaultTypeScale({ display: fonts.serif, body: fonts.sans, mono: fonts.mono }),
    motif: "\u2727 Souk",
    preview: ["#1A5276", "#D4A03C", "#C0653A"],
  },

  polaroid: {
    id: "polaroid",
    name: "Polaroid",
    tagline: "Faded film and warm nostalgia",
    description: "For the photographer who shoots on film, hoards vintage cameras, and thinks every digital photo looks too sharp. Faded warm tones, soft grain, the yellow of old Polaroid borders.",
    designer: "Dehlya Studio", year: "2026", mode: "light",
    inspiration: "Polaroid SX-70, faded family photos, golden hour film, Kodak Portra 400, shoebox memories.",
    features: ["Warm faded color palette", "Soft cream backgrounds", "Vintage amber accents", "Nostalgic, slightly washed feel"],
    useCases: ["Photography portfolios", "Wedding sites", "Memory/journal apps", "Vintage brands"],
    tokens: {
      background: "#FAF5EE", surface: "#FFFDF8", surfaceAlt: "#F2EAD8", border: "#E0D4BE",
      text: "#3A3028", textMuted: "#8A7A68", textInverse: "#FFFDF8",
      primary: "#B87333", primaryContrast: "#FFFDF8", secondary: "#8B7355", accent: "#D4956A",
      success: "#7A9E6D", warning: "#D4956A", danger: "#B85A4A",
      radius: "0.25rem", radiusLg: "0.5rem",
      shadow: "0 4px 16px -6px rgba(58,48,40,0.12)", shadowLg: "0 16px 48px -12px rgba(58,48,40,0.18)",
      fontSans: fonts.sans, fontDisplay: fonts.serif, fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #B87333 0%, #D4956A 50%, #F2EAD8 100%)",
      pattern: "radial-gradient(rgba(184,115,51,0.04) 1px, transparent 1px)",
    },
    typeScale: defaultTypeScale({ display: fonts.serif, body: fonts.sans, mono: fonts.mono, displayWeight: 600 }),
    motif: "\u25fb Polaroid",
    preview: ["#B87333", "#D4956A", "#FAF5EE"],
  },

  greenhouse: {
    id: "greenhouse",
    name: "Greenhouse",
    tagline: "Glass, humidity, and botanical labels",
    description: "For the person who has 47 houseplants and knows all their Latin names. Deep botanical green, glass structure feel, specimen-label typography. The air is warm and humid.",
    designer: "Dehlya Studio", year: "2026", mode: "light",
    inspiration: "Kew Gardens, Victorian glasshouses, botanical illustrations, plant ID tags, terrariums.",
    features: ["Deep botanical greens", "Glass/translucent surfaces", "Specimen label typography", "Warm humid atmosphere"],
    useCases: ["Plant shops", "Botanical blogs", "Sustainability sites", "Garden planning tools"],
    tokens: {
      background: "#F0F5EE", surface: "#FAFCFA", surfaceAlt: "#E4ECE2", border: "#C4D4C0",
      text: "#1A2E1A", textMuted: "#5A7258", textInverse: "#FAFCFA",
      primary: "#2D5A27", primaryContrast: "#FAFCFA", secondary: "#8B6F47", accent: "#A8C496",
      success: "#2D5A27", warning: "#C4A44A", danger: "#8B3A3A",
      radius: "0.25rem", radiusLg: "0.5rem",
      shadow: "0 4px 16px -6px rgba(26,46,26,0.12)", shadowLg: "0 16px 48px -12px rgba(26,46,26,0.18)",
      fontSans: fonts.sans, fontDisplay: fonts.serif, fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #2D5A27 0%, #A8C496 100%)",
      pattern: "radial-gradient(rgba(45,90,39,0.05) 1.5px, transparent 1.5px)",
    },
    typeScale: defaultTypeScale({ display: fonts.serif, body: fonts.sans, mono: fonts.mono }),
    motif: "\ud83c\udf31 Greenhouse",
    preview: ["#2D5A27", "#A8C496", "#F0F5EE"],
  },

  vinyl: {
    id: "vinyl",
    name: "Vinyl",
    tagline: "Warm amber in a record store at midnight",
    description: "For the person who spends Saturday afternoons flipping through crates of vinyl, argues about pressings, and thinks streaming killed album art. Warm amber glow, charcoal shelves, analog warmth.",
    designer: "Dehlya Studio", year: "2026", mode: "dark",
    inspiration: "Record stores at closing time, tube amplifier glow, album liner notes, 70s hi-fi, warm incandescent light.",
    features: ["Warm amber + charcoal palette", "Analog warmth feeling", "Rich, deep surfaces", "Orange accent glow"],
    useCases: ["Music blogs", "Record label sites", "Podcast platforms", "Audio equipment reviews"],
    tokens: {
      background: "#1A1612", surface: "#24201A", surfaceAlt: "#2E2820", border: "#3E3428",
      text: "#E8DDD0", textMuted: "#A89880", textInverse: "#1A1612",
      primary: "#E8A040", primaryContrast: "#1A1612", secondary: "#D07830", accent: "#F0C870",
      success: "#7AAA55", warning: "#E8A040", danger: "#CC5544",
      radius: "0.375rem", radiusLg: "0.75rem",
      shadow: "0 4px 20px -6px rgba(0,0,0,0.5), 0 0 0 1px rgba(232,160,64,0.08)", shadowLg: "0 20px 60px -15px rgba(232,160,64,0.15)",
      fontSans: fonts.sans, fontDisplay: fonts.serif, fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #E8A040 0%, #D07830 50%, #1A1612 100%)",
      pattern: "repeating-linear-gradient(90deg, rgba(232,160,64,0.03) 0 1px, transparent 1px 40px)",
    },
    typeScale: defaultTypeScale({ display: fonts.serif, body: fonts.sans, mono: fonts.mono }),
    motif: "\u266b Vinyl",
    preview: ["#E8A040", "#D07830", "#1A1612"],
  },

  tatami: {
    id: "tatami",
    name: "Tatami",
    tagline: "Rice paper, bamboo, and zen emptiness",
    description: "For the person who thinks the best design is the most you can remove. Japanese minimalism \u2014 rice paper textures, bamboo accents, generous negative space. Ma (\u9593) \u2014 the beauty of empty intervals.",
    designer: "Dehlya Studio", year: "2026", mode: "light",
    inspiration: "Muji, Japanese tea rooms, Wabi-sabi, tatami mat texture, shoji screens, ikebana.",
    features: ["Ultra-minimal, maximum whitespace", "Rice paper warmth", "Bamboo/straw accents", "Almost no color"],
    useCases: ["Minimalist portfolios", "Zen/wellness sites", "Japanese restaurants", "Meditation apps"],
    tokens: {
      background: "#F5F0E8", surface: "#FDFAF4", surfaceAlt: "#EDE8DE", border: "#D8D0C0",
      text: "#2A2520", textMuted: "#8A8070", textInverse: "#FDFAF4",
      primary: "#5A5040", primaryContrast: "#FDFAF4", secondary: "#8A7A60", accent: "#B8A878",
      success: "#6A8A55", warning: "#B8A040", danger: "#9A4A3A",
      radius: "0.125rem", radiusLg: "0.25rem",
      shadow: "0 2px 12px -4px rgba(42,37,32,0.08)", shadowLg: "0 12px 36px -10px rgba(42,37,32,0.12)",
      fontSans: fonts.sans, fontDisplay: fonts.serif, fontMono: fonts.mono,
      gradient: "linear-gradient(180deg, #5A5040 0%, #F5F0E8 100%)",
      pattern: "repeating-linear-gradient(90deg, rgba(90,80,64,0.03) 0 1px, transparent 1px 20px)",
    },
    typeScale: defaultTypeScale({ display: fonts.serif, body: fonts.sans, mono: fonts.mono, displayWeight: 400, bodyWeight: 300 }),
    motif: "\u9593 Tatami",
    preview: ["#5A5040", "#B8A878", "#F5F0E8"],
  },

  carnival: {
    id: "carnival",
    name: "Carnival",
    tagline: "Confetti, drums, and golden light",
    description: "For the person who lights up every room \u2014 Brazilian carnival energy channeled into a design system. Rich golds, vibrant greens, deep purples. Life is a celebration and your website should be too.",
    designer: "Dehlya Studio", year: "2026", mode: "dark",
    inspiration: "Rio de Janeiro carnival, samba rhythms, gold sequins, tropical feathers, caipirinha sunsets.",
    features: ["Rich gold + vibrant green + purple", "Celebratory energy", "Bold contrasts", "Festival warmth"],
    useCases: ["Event sites", "Festival pages", "Entertainment platforms", "Cultural celebrations"],
    tokens: {
      background: "#1A0A20", surface: "#241430", surfaceAlt: "#2E1A3E", border: "#4A2D60",
      text: "#F5E8FF", textMuted: "#B898D4", textInverse: "#1A0A20",
      primary: "#FFD700", primaryContrast: "#1A0A20", secondary: "#00CC66", accent: "#FF4488",
      success: "#00CC66", warning: "#FFD700", danger: "#FF3355",
      radius: "0.5rem", radiusLg: "1rem",
      shadow: "0 4px 20px -6px rgba(255,215,0,0.2)", shadowLg: "0 20px 60px -15px rgba(255,215,0,0.25)",
      fontSans: fonts.sans, fontDisplay: fonts.grotesk, fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #FFD700 0%, #00CC66 33%, #FF4488 66%, #7B2DFF 100%)",
      pattern: "radial-gradient(rgba(255,215,0,0.06) 2px, transparent 2px), radial-gradient(rgba(0,204,102,0.04) 2px, transparent 2px)",
    },
    typeScale: defaultTypeScale({ display: fonts.grotesk, body: fonts.sans, mono: fonts.mono }),
    motif: "\ud83c\udf89 Carnival",
    preview: ["#FFD700", "#00CC66", "#FF4488"],
  },

  darkroom: {
    id: "darkroom",
    name: "Darkroom",
    tagline: "Red safe-light and silver halide",
    description: "For the analog photographer who still develops their own film. Deep darkness with the red glow of a safe-light, the chemical smell of developer, the magic of an image appearing on paper.",
    designer: "Dehlya Studio", year: "2026", mode: "dark",
    inspiration: "Photographic darkrooms, red safe-lights, silver gelatin prints, contact sheets, chemical trays.",
    features: ["Deep black with red safe-light glow", "Silver/gray accents", "Photographic paper whites", "Intimate, focused feel"],
    useCases: ["Photography portfolios", "Art galleries", "Film sites", "Moody personal blogs"],
    tokens: {
      background: "#0A0808", surface: "#141010", surfaceAlt: "#1A1414", border: "#2A2020",
      text: "#E8E0D8", textMuted: "#988880", textInverse: "#0A0808",
      primary: "#CC3333", primaryContrast: "#E8E0D8", secondary: "#888080", accent: "#E8D0C0",
      success: "#669955", warning: "#CC9933", danger: "#CC3333",
      radius: "0.125rem", radiusLg: "0.25rem",
      shadow: "0 4px 16px -6px rgba(204,51,51,0.15)", shadowLg: "0 16px 48px -12px rgba(204,51,51,0.2)",
      fontSans: fonts.sans, fontDisplay: fonts.grotesk, fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #CC3333 0%, #0A0808 100%)",
      pattern: "radial-gradient(rgba(204,51,51,0.04) 1px, transparent 1px)",
    },
    typeScale: defaultTypeScale({ display: fonts.grotesk, body: fonts.sans, mono: fonts.mono }),
    motif: "\u25d0 Darkroom",
    preview: ["#CC3333", "#888080", "#0A0808"],
  },

  chalk: {
    id: "chalk",
    name: "Chalk",
    tagline: "Green board, white dust, honest simplicity",
    description: "For the teacher at heart \u2014 someone who explains things clearly and believes in fundamentals. Deep green chalkboard, white chalk, the satisfying scratch of writing something that helps someone understand.",
    designer: "Dehlya Studio", year: "2026", mode: "dark",
    inspiration: "Classroom blackboards, chalk dust, math proofs, the teacher who changed your life, MIT lecture halls.",
    features: ["Dark green board background", "White chalk text", "Handwritten energy", "Educational, honest feel"],
    useCases: ["Educational platforms", "Course landing pages", "Tutorial blogs", "Math/science sites"],
    tokens: {
      background: "#1A3A2A", surface: "#224432", surfaceAlt: "#2A5038", border: "#3A6048",
      text: "#F0F0E8", textMuted: "#A8C0A8", textInverse: "#1A3A2A",
      primary: "#F0F0E8", primaryContrast: "#1A3A2A", secondary: "#FFE066", accent: "#FF8866",
      success: "#88DD88", warning: "#FFE066", danger: "#FF6655",
      radius: "0.125rem", radiusLg: "0.25rem",
      shadow: "0 2px 10px -4px rgba(0,0,0,0.4)", shadowLg: "0 10px 30px -10px rgba(0,0,0,0.5)",
      fontSans: fonts.sans, fontDisplay: fonts.grotesk, fontMono: fonts.mono,
      gradient: "linear-gradient(180deg, #1A3A2A 0%, #2A5038 100%)",
      pattern: "radial-gradient(rgba(240,240,232,0.03) 1px, transparent 1px)",
    },
    typeScale: defaultTypeScale({ display: fonts.grotesk, body: fonts.sans, mono: fonts.mono }),
    motif: "\u270e Chalk",
    preview: ["#F0F0E8", "#FFE066", "#1A3A2A"],
  },

  sunset: {
    id: "sunset",
    name: "Sunset",
    tagline: "Golden hour, every hour",
    description: "For the golden-hour photographer, the person who pulls over for sunsets, who believes the best light lasts only minutes. Warm amber, peach, rose \u2014 the sky right before it goes dark.",
    designer: "Dehlya Studio", year: "2026", mode: "light",
    inspiration: "Golden hour photography, desert sunsets, warm Instagram filters, sand dunes at dusk, campfire glow.",
    features: ["Warm amber + peach + rose", "Golden hour glow", "Soft warm gradients", "Dreamy, warm atmosphere"],
    useCases: ["Photography sites", "Lifestyle brands", "Wedding sites", "Warm personal blogs"],
    tokens: {
      background: "#FFF8F0", surface: "#FFFFFF", surfaceAlt: "#FFF0E0", border: "#F0D8C0",
      text: "#3A2820", textMuted: "#8A6A55", textInverse: "#FFFFFF",
      primary: "#E07040", primaryContrast: "#FFFFFF", secondary: "#D4956A", accent: "#E8A07A",
      success: "#6A9E55", warning: "#E8A040", danger: "#CC4433",
      radius: "1rem", radiusLg: "1.5rem",
      shadow: "0 4px 20px -6px rgba(224,112,64,0.2)", shadowLg: "0 20px 60px -15px rgba(224,112,64,0.25)",
      fontSans: fonts.sans, fontDisplay: fonts.serif, fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #E07040 0%, #E8A07A 50%, #FFD4B8 100%)",
      pattern: "radial-gradient(rgba(224,112,64,0.06) 1.5px, transparent 1.5px)",
    },
    typeScale: defaultTypeScale({ display: fonts.serif, body: fonts.sans, mono: fonts.mono, displayWeight: 600 }),
    motif: "\u2600 Sunset",
    preview: ["#E07040", "#E8A07A", "#FFF8F0"],
  },

  arctic: {
    id: "arctic",
    name: "Arctic",
    tagline: "Ice, light, and crystalline silence",
    description: "For the person who finds peace in cold, bright emptiness \u2014 fresh snow, ice blue sky, the silence of a frozen lake. Ultra-clean, ultra-bright, with crystalline blue accents that feel like breathing cold air.",
    designer: "Dehlya Studio", year: "2026", mode: "light",
    inspiration: "Arctic landscapes, fresh snowfall, ice caves, Scandinavian winter, northern light reflections.",
    features: ["Bright white + ice blue", "Crystalline clean feel", "Ultra-high contrast", "Spacious, breathing layout"],
    useCases: ["Clean SaaS products", "Health/wellness apps", "Minimalist portfolios", "Corporate sites that need soul"],
    tokens: {
      background: "#F8FAFE", surface: "#FFFFFF", surfaceAlt: "#EEF4FA", border: "#D4E2F0",
      text: "#1A2A3A", textMuted: "#6A8AA8", textInverse: "#FFFFFF",
      primary: "#2B8DD6", primaryContrast: "#FFFFFF", secondary: "#5BA4D9", accent: "#A0D4F0",
      success: "#44BB88", warning: "#DDAA44", danger: "#DD5555",
      radius: "0.5rem", radiusLg: "1rem",
      shadow: "0 4px 16px -6px rgba(43,141,214,0.12)", shadowLg: "0 16px 48px -12px rgba(43,141,214,0.18)",
      fontSans: fonts.sans, fontDisplay: fonts.grotesk, fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #2B8DD6 0%, #A0D4F0 50%, #F8FAFE 100%)",
      pattern: "radial-gradient(rgba(43,141,214,0.04) 1px, transparent 1px)",
    },
    typeScale: defaultTypeScale({ display: fonts.grotesk, body: fonts.sans, mono: fonts.mono }),
    motif: "\u274a Arctic",
    preview: ["#2B8DD6", "#A0D4F0", "#F8FAFE"],
  },

  // ===============================================
  //  BATCH 4 — more worlds, more people
  // ===============================================

  alpine: {
    id: "alpine",
    name: "Alpine",
    tagline: "Mountain air and chalet wood",
    description: "For someone who lives where the air is thin and the views are endless. Swiss Alpine \u2014 warm pine wood, crisp air blue, snow white, the smell of Raclette and woodfire. This one's personal.",
    designer: "Dehlya Studio", year: "2026", mode: "light",
    inspiration: "Swiss Valais, mountain chalets, pine forests, Alpine meadows, fresh snow on peaks, fondue evenings.",
    features: ["Pine wood + snow white + sky blue", "Mountain air freshness", "Warm chalet touches", "Swiss precision meets nature"],
    useCases: ["Mountain tourism", "Swiss brands", "Outdoor gear", "Chalet rentals"],
    tokens: {
      background: "#F5F2ED", surface: "#FFFFFF", surfaceAlt: "#EDE8DF", border: "#D4CCC0",
      text: "#2A2420", textMuted: "#7A6E62", textInverse: "#FFFFFF",
      primary: "#4A7B9A", primaryContrast: "#FFFFFF", secondary: "#8B6F47", accent: "#A4C4AA",
      success: "#5A8A60", warning: "#D4A040", danger: "#B85A4A",
      radius: "0.375rem", radiusLg: "0.75rem",
      shadow: "0 4px 18px -6px rgba(42,36,32,0.14)", shadowLg: "0 20px 50px -15px rgba(42,36,32,0.2)",
      fontSans: fonts.sans, fontDisplay: fonts.grotesk, fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #4A7B9A 0%, #A4C4AA 50%, #F5F2ED 100%)",
      pattern: "radial-gradient(rgba(74,123,154,0.05) 1px, transparent 1px), radial-gradient(rgba(139,111,71,0.04) 1px, transparent 1px)",
    },
    typeScale: defaultTypeScale({ display: fonts.grotesk, body: fonts.sans, mono: fonts.mono }),
    motif: "\u26f0 Alpine",
    preview: ["#4A7B9A", "#8B6F47", "#A4C4AA"],
  },

  abyss: {
    id: "abyss",
    name: "Abyss",
    tagline: "Deep ocean, bioluminescent glow",
    description: "For someone drawn to the unknown depths \u2014 the crushing dark of deep ocean where the only light comes from creatures that make their own. Deep navy, bioluminescent teal, the silence of pressure.",
    designer: "Dehlya Studio", year: "2026", mode: "dark",
    inspiration: "Deep sea trenches, bioluminescent jellyfish, submarine control rooms, Jacques Cousteau, abyssal plains.",
    features: ["Abyssal navy + bioluminescent teal", "Deep pressure feeling", "Glowing accent elements", "Mysterious, vast atmosphere"],
    useCases: ["Science sites", "Data visualization", "Marine biology", "Mystery/thriller brands"],
    tokens: {
      background: "#060D18", surface: "#0C1525", surfaceAlt: "#121D32", border: "#1A2844",
      text: "#C8D8E8", textMuted: "#6888A8", textInverse: "#060D18",
      primary: "#00D4AA", primaryContrast: "#060D18", secondary: "#0088CC", accent: "#44FFCC",
      success: "#00DD88", warning: "#DDAA44", danger: "#FF4466",
      radius: "0.5rem", radiusLg: "1rem",
      shadow: "0 0 20px rgba(0,212,170,0.1), 0 4px 16px rgba(0,0,0,0.5)", shadowLg: "0 0 50px rgba(0,212,170,0.15), 0 20px 60px rgba(0,0,0,0.6)",
      fontSans: fonts.sans, fontDisplay: fonts.grotesk, fontMono: fonts.mono,
      gradient: "linear-gradient(180deg, #00D4AA 0%, #0088CC 50%, #060D18 100%)",
      pattern: "radial-gradient(rgba(0,212,170,0.04) 1px, transparent 1px)",
    },
    typeScale: defaultTypeScale({ display: fonts.grotesk, body: fonts.sans, mono: fonts.mono }),
    motif: "\u25c9 Abyss",
    preview: ["#00D4AA", "#0088CC", "#060D18"],
  },

  harvest: {
    id: "harvest",
    name: "Harvest",
    tagline: "Autumn leaves and pumpkin warmth",
    description: "For someone who thinks October is the best month \u2014 the crunch of leaves, the warmth of cider, the golden-orange-burgundy palette of a forest turning. Cozy, rich, seasonal perfection.",
    designer: "Dehlya Studio", year: "2026", mode: "light",
    inspiration: "New England autumn, pumpkin patches, apple orchards, wool blankets, Thanksgiving tables.",
    features: ["Burgundy + burnt orange + gold", "Autumn warmth", "Rich seasonal palette", "Cozy, layered feel"],
    useCases: ["Food blogs", "Seasonal campaigns", "Artisan brands", "Cozy personal sites"],
    tokens: {
      background: "#FAF4EC", surface: "#FFFFFF", surfaceAlt: "#F2E8D8", border: "#DCC8A8",
      text: "#2E1E14", textMuted: "#7A5E48", textInverse: "#FFFFFF",
      primary: "#8B3A2F", primaryContrast: "#FAF4EC", secondary: "#CC7A33", accent: "#D4A040",
      success: "#5A7A40", warning: "#CC7A33", danger: "#8B3A2F",
      radius: "0.5rem", radiusLg: "1rem",
      shadow: "0 4px 18px -6px rgba(46,30,20,0.15)", shadowLg: "0 20px 50px -15px rgba(46,30,20,0.22)",
      fontSans: fonts.sans, fontDisplay: fonts.serif, fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #8B3A2F 0%, #CC7A33 50%, #D4A040 100%)",
      pattern: "radial-gradient(rgba(139,58,47,0.05) 1.5px, transparent 1.5px)",
    },
    typeScale: defaultTypeScale({ display: fonts.serif, body: fonts.sans, mono: fonts.mono, displayWeight: 700 }),
    motif: "\ud83c\udf42 Harvest",
    preview: ["#8B3A2F", "#CC7A33", "#D4A040"],
  },

  noire: {
    id: "noire",
    name: "Noire",
    tagline: "Smoke, shadows, and a single desk lamp",
    description: "For the film noir fan \u2014 someone who appreciates dramatic lighting, long shadows, and stories told in whispers. Black, white, and every gray in between. The only color: a cigarette ember.",
    designer: "Dehlya Studio", year: "2026", mode: "dark",
    inspiration: "Film noir, Humphrey Bogart, venetian blind shadows, detective fiction, black-and-white photography.",
    features: ["True monochrome (no color except one red)", "High drama contrast", "Cinematic shadows", "Smoky atmosphere"],
    useCases: ["Photography portfolios", "Mystery/thriller", "Film review sites", "Dramatic personal brands"],
    tokens: {
      background: "#0A0A0A", surface: "#141414", surfaceAlt: "#1E1E1E", border: "#2A2A2A",
      text: "#E8E8E8", textMuted: "#888888", textInverse: "#0A0A0A",
      primary: "#E8E8E8", primaryContrast: "#0A0A0A", secondary: "#AAAAAA", accent: "#CC3333",
      success: "#88AA88", warning: "#CCAA44", danger: "#CC3333",
      radius: "0rem", radiusLg: "0.125rem",
      shadow: "0 4px 20px -4px rgba(0,0,0,0.8)", shadowLg: "0 20px 60px -10px rgba(0,0,0,0.9)",
      fontSans: fonts.sans, fontDisplay: fonts.serif, fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #E8E8E8 0%, #0A0A0A 100%)",
      pattern: "repeating-linear-gradient(90deg, rgba(255,255,255,0.01) 0 1px, transparent 1px 4px)",
    },
    typeScale: defaultTypeScale({ display: fonts.serif, body: fonts.sans, mono: fonts.mono, displayWeight: 700 }),
    motif: "\u25c6 Noire",
    preview: ["#E8E8E8", "#CC3333", "#0A0A0A"],
  },

  pixelart: {
    id: "pixelart",
    name: "Pixel Art",
    tagline: "8-bit nostalgia, 16 colors of pure joy",
    description: "For the retro gamer who thinks 64\u00d764 sprites have more soul than ray-traced cinematics. Bright primary colors, zero anti-aliasing energy, system font, chunky pixels. Game over? Insert coin.",
    designer: "Dehlya Studio", year: "2026", mode: "dark",
    inspiration: "NES, Game Boy, early internet, pixel art communities, chiptune music, retro game UIs.",
    features: ["Bright primary game colors", "Zero border radius (pixel perfect)", "Monospaced system font", "Retro game UI energy"],
    useCases: ["Indie game sites", "Retro-themed projects", "Game dev portfolios", "Nostalgia brands"],
    tokens: {
      background: "#1A1A2E", surface: "#222240", surfaceAlt: "#2A2A50", border: "#3A3A60",
      text: "#EEEEFF", textMuted: "#8888AA", textInverse: "#1A1A2E",
      primary: "#FF4444", primaryContrast: "#FFFFFF", secondary: "#4444FF", accent: "#44FF44",
      success: "#44FF44", warning: "#FFFF44", danger: "#FF4444",
      radius: "0rem", radiusLg: "0rem",
      shadow: "4px 4px 0 0 rgba(0,0,0,0.5)", shadowLg: "8px 8px 0 0 rgba(0,0,0,0.5)",
      fontSans: fonts.mono, fontDisplay: fonts.mono, fontMono: fonts.mono,
      gradient: "linear-gradient(180deg, #FF4444 0%, #4444FF 50%, #44FF44 100%)",
      pattern: "linear-gradient(to right, rgba(255,255,255,0.02) 1px, transparent 1px), linear-gradient(to bottom, rgba(255,255,255,0.02) 1px, transparent 1px)",
    },
    typeScale: defaultTypeScale({ display: fonts.mono, body: fonts.mono, mono: fonts.mono }),
    motif: "\u25b6 PIXEL",
    preview: ["#FF4444", "#4444FF", "#44FF44"],
  },

  zine: {
    id: "zine",
    name: "Zine",
    tagline: "Photocopied, stapled, handed out for free",
    description: "For the punk spirit \u2014 DIY, anti-establishment, made-at-the-copy-shop energy. Rough edges, high contrast black-and-white, one highlight color from a marker. Perfection is not the point.",
    designer: "Dehlya Studio", year: "2026", mode: "light",
    inspiration: "DIY punk zines, riot grrrl, photocopied flyers, ransom note typography, underground press.",
    features: ["High contrast black on off-white", "Raw, unpolished aesthetic", "Marker highlight color", "Imperfect, handmade energy"],
    useCases: ["Zine archives", "Underground music", "Activist sites", "Anti-corporate brands"],
    tokens: {
      background: "#F0ECE4", surface: "#F8F4EE", surfaceAlt: "#E8E0D4", border: "#1A1A1A",
      text: "#1A1A1A", textMuted: "#5A5A5A", textInverse: "#F0ECE4",
      primary: "#1A1A1A", primaryContrast: "#F0ECE4", secondary: "#5A5A5A", accent: "#FF3399",
      success: "#338833", warning: "#CC8800", danger: "#CC0000",
      radius: "0rem", radiusLg: "0rem",
      shadow: "3px 3px 0 0 #1A1A1A", shadowLg: "6px 6px 0 0 #1A1A1A",
      fontSans: `system-ui, sans-serif`, fontDisplay: fonts.mono, fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #1A1A1A 0%, #FF3399 100%)",
      pattern: "repeating-linear-gradient(45deg, rgba(26,26,26,0.03) 0 2px, transparent 2px 8px)",
    },
    typeScale: defaultTypeScale({ display: fonts.mono, body: `system-ui, sans-serif`, mono: fonts.mono, displayWeight: 900 }),
    motif: "\u2715 ZINE",
    preview: ["#1A1A1A", "#FF3399", "#F0ECE4"],
  },

  lab: {
    id: "lab",
    name: "Lab",
    tagline: "White coats, clean data, precise results",
    description: "For the scientist who brings the same rigor to their website as to their research. Clinical white, precise blue accents, data-table energy. Every pixel has a hypothesis behind it.",
    designer: "Dehlya Studio", year: "2026", mode: "light",
    inspiration: "Research labs, scientific papers, data dashboards, microscope views, Nature journal layout.",
    features: ["Clinical white + precise blue", "Data-table typography", "Ultra-clean surfaces", "Scientific rigor feel"],
    useCases: ["Research portfolios", "Data dashboards", "Science blogs", "Healthcare tools"],
    tokens: {
      background: "#F8FAFB", surface: "#FFFFFF", surfaceAlt: "#F0F4F8", border: "#D8E0E8",
      text: "#1A2633", textMuted: "#5A7088", textInverse: "#FFFFFF",
      primary: "#2563EB", primaryContrast: "#FFFFFF", secondary: "#6366F1", accent: "#06B6D4",
      success: "#10B981", warning: "#F59E0B", danger: "#EF4444",
      radius: "0.375rem", radiusLg: "0.5rem",
      shadow: "0 1px 3px rgba(0,0,0,0.06), 0 0 0 1px rgba(0,0,0,0.04)", shadowLg: "0 10px 30px -5px rgba(0,0,0,0.1)",
      fontSans: fonts.sans, fontDisplay: fonts.sans, fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #2563EB 0%, #06B6D4 100%)",
      pattern: "linear-gradient(to right, rgba(37,99,235,0.03) 1px, transparent 1px), linear-gradient(to bottom, rgba(37,99,235,0.03) 1px, transparent 1px)",
    },
    typeScale: defaultTypeScale({ display: fonts.sans, body: fonts.sans, mono: fonts.mono, displayWeight: 700 }),
    motif: "\u2697 Lab",
    preview: ["#2563EB", "#06B6D4", "#F8FAFB"],
  },

  terrace: {
    id: "terrace",
    name: "Terrace",
    tagline: "Mediterranean sun on white stone",
    description: "For the person who falls asleep to the sound of Mediterranean waves and wakes up to olive groves. Sun-bleached white walls, terracotta pots, bougainvillea pink, azure sea glimpses.",
    designer: "Dehlya Studio", year: "2026", mode: "light",
    inspiration: "Santorini, Amalfi Coast, Greek tavernas, whitewashed walls, bougainvillea, fresh lemons.",
    features: ["Sun-bleached white + azure blue", "Terracotta + bougainvillea accents", "Mediterranean warmth", "Bright, airy, open feel"],
    useCases: ["Travel sites", "Restaurant/cafe", "Hospitality", "Lifestyle brands"],
    tokens: {
      background: "#FEFCF8", surface: "#FFFFFF", surfaceAlt: "#F5F0E8", border: "#E0D8CC",
      text: "#2A2018", textMuted: "#7A6A58", textInverse: "#FFFFFF",
      primary: "#1E6FA0", primaryContrast: "#FFFFFF", secondary: "#C0653A", accent: "#D44080",
      success: "#4A8A55", warning: "#D4A030", danger: "#C04040",
      radius: "0.75rem", radiusLg: "1.5rem",
      shadow: "0 4px 18px -6px rgba(42,32,24,0.12)", shadowLg: "0 20px 50px -15px rgba(42,32,24,0.18)",
      fontSans: fonts.sans, fontDisplay: fonts.serif, fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #1E6FA0 0%, #D44080 50%, #C0653A 100%)",
      pattern: "radial-gradient(rgba(30,111,160,0.04) 1px, transparent 1px)",
    },
    typeScale: defaultTypeScale({ display: fonts.serif, body: fonts.sans, mono: fonts.mono, displayWeight: 600 }),
    motif: "\u263c Terrace",
    preview: ["#1E6FA0", "#D44080", "#C0653A"],
  },

  aurora: {
    id: "aurora",
    name: "Aurora",
    tagline: "Northern lights dancing on dark velvet",
    description: "For the person who's seen the aurora borealis and never recovered. Green-purple-blue light ribbons dancing on the darkest sky. Ethereal, shifting, never quite the same twice.",
    designer: "Dehlya Studio", year: "2026", mode: "dark",
    inspiration: "Northern lights in Norway, magnetic field visualization, Arctic night sky, glacial ice reflecting light.",
    features: ["Green-purple-blue aurora gradient", "Deep dark sky background", "Ethereal shifting feel", "Magical, rare atmosphere"],
    useCases: ["Creative portfolios", "Music sites", "Fantasy/gaming", "Night photography"],
    tokens: {
      background: "#0A0E18", surface: "#121828", surfaceAlt: "#1A2238", border: "#2A3350",
      text: "#D8E0F0", textMuted: "#7888AA", textInverse: "#0A0E18",
      primary: "#44DD88", primaryContrast: "#0A0E18", secondary: "#8855DD", accent: "#44AAFF",
      success: "#44DD88", warning: "#DDAA44", danger: "#DD4466",
      radius: "0.5rem", radiusLg: "1rem",
      shadow: "0 0 25px rgba(68,221,136,0.12), 0 4px 16px rgba(0,0,0,0.4)", shadowLg: "0 0 60px rgba(68,221,136,0.15), 0 0 40px rgba(136,85,221,0.1)",
      fontSans: fonts.sans, fontDisplay: fonts.grotesk, fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #44DD88 0%, #44AAFF 30%, #8855DD 60%, #DD4488 100%)",
      pattern: "radial-gradient(ellipse at 30% 40%, rgba(68,221,136,0.06), transparent 40%), radial-gradient(ellipse at 70% 60%, rgba(136,85,221,0.05), transparent 40%)",
    },
    typeScale: defaultTypeScale({ display: fonts.grotesk, body: fonts.sans, mono: fonts.mono }),
    motif: "\u2727 Aurora",
    preview: ["#44DD88", "#8855DD", "#44AAFF"],
  },

  espresso: {
    id: "espresso",
    name: "Espresso",
    tagline: "Italian marble counter, morning ritual",
    description: "For the person who orders the same espresso every morning at the same marble counter. LIGHT mode \u2014 white marble, espresso brown accents, crema gold. The precision of Italian caf\u00e9 culture.",
    designer: "Dehlya Studio", year: "2026", mode: "light",
    inspiration: "Italian espresso bars, marble countertops, morning rituals in Milan, crema foam art, Bialetti mokas.",
    features: ["White marble + espresso brown", "Crema gold accents", "Italian precision feel", "Clean but warm light mode"],
    useCases: ["Caf\u00e9/restaurant sites", "Premium products", "Morning routine apps", "Italian-inspired brands"],
    tokens: {
      background: "#FAF7F2", surface: "#FFFFFF", surfaceAlt: "#F2EDE4", border: "#DDD4C8",
      text: "#2A1E14", textMuted: "#7A6855", textInverse: "#FFFFFF",
      primary: "#5C3D2E", primaryContrast: "#FAF7F2", secondary: "#8B6F47", accent: "#C8A050",
      success: "#5A8A50", warning: "#C8A050", danger: "#AA4433",
      radius: "0.25rem", radiusLg: "0.5rem",
      shadow: "0 2px 12px -4px rgba(42,30,20,0.1)", shadowLg: "0 12px 36px -8px rgba(42,30,20,0.15)",
      fontSans: fonts.sans, fontDisplay: fonts.serif, fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #5C3D2E 0%, #C8A050 100%)",
      pattern: "radial-gradient(rgba(92,61,46,0.04) 1px, transparent 1px)",
    },
    typeScale: defaultTypeScale({ display: fonts.serif, body: fonts.sans, mono: fonts.mono, displayWeight: 600 }),
    motif: "\u25c9 Espresso",
    preview: ["#5C3D2E", "#C8A050", "#FAF7F2"],
  },

  // ─────────── Batch 5 — Engineering / technical ───────────

  datacycle: {
    id: "datacycle",
    name: "Data Cycle",
    tagline: "Engineering docs with opinions",
    description: "For the technical writer who treats documentation as architecture. Warm cream canvas, sharp zero-radius edges, monospace labels announcing themselves in uppercase, a thin forest-green topline reminding you someone cared. Medallion architecture — bronze to silver to gold — without the dashboard cliche.",
    designer: "Dehlya Studio", year: "2026", mode: "light",
    inspiration: "Medallion data architecture, Stripe docs, Linear changelogs, engineering whitepapers, HES-SO technical reports.",
    features: ["Warm cream + black ink", "Sharp rectangular edges", "Monospace UI labels", "Bronze/silver/gold medallion accent"],
    useCases: ["Data project docs", "Engineering portfolios", "Technical case studies", "Internal dashboards"],
    tokens: {
      background: "#F4F1EA", surface: "#FAF8F3", surfaceAlt: "#EBE8E0", border: "#D4D2CC",
      text: "#1A1A1A", textMuted: "#6B6B6B", textInverse: "#F4F1EA",
      primary: "#1A1A1A", primaryContrast: "#F4F1EA", secondary: "#8B6914", accent: "#1F4E3D",
      success: "#2E7D32", warning: "#E65100", danger: "#B71C1C",
      radius: "0", radiusLg: "0",
      shadow: "0 1px 0 rgba(26,26,26,0.04), 0 1px 3px rgba(26,26,26,0.06)",
      shadowLg: "0 8px 24px -4px rgba(26,26,26,0.08)",
      fontSans: fonts.sans, fontDisplay: fonts.sans, fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #8B6914 0%, #A8A8A8 50%, #D4AF37 100%)",
      pattern: "linear-gradient(to right, rgba(26,26,26,0.04) 1px, transparent 1px), linear-gradient(to bottom, rgba(26,26,26,0.04) 1px, transparent 1px)",
    },
    typeScale: defaultTypeScale({ display: fonts.sans, body: fonts.sans, mono: fonts.mono, displayWeight: 800 }),
    motif: "\u2192 data-cycle",
    preview: ["#1A1A1A", "#8B6914", "#1F4E3D"],
  },

  blueprint: {
    id: "blueprint",
    name: "Blueprint",
    tagline: "Technical drawings on cyanotype paper",
    description: "For the systems thinker who sketches architecture before writing a line of code. Deep navy cyanotype background, cool cyan linework, orange pencil-mark accents for the things that matter. Every page feels like a draft that's been reviewed three times.",
    designer: "Dehlya Studio", year: "2026", mode: "dark",
    inspiration: "Architectural blueprints, cyanotype prints, technical drafting, isometric grids, engineering schematics.",
    features: ["Cyanotype navy + cyan linework", "Orange pencil-mark accents", "Grid pattern overlay", "Monospace-forward type"],
    useCases: ["Engineering portfolios", "Architecture practices", "System design docs", "Technical diagrams"],
    tokens: {
      background: "#0A1929", surface: "#112A3F", surfaceAlt: "#1A3952", border: "#2A5580",
      text: "#D0E4F5", textMuted: "#7FA5C8", textInverse: "#0A1929",
      primary: "#4FC3F7", primaryContrast: "#0A1929", secondary: "#FFFFFF", accent: "#FFB74D",
      success: "#66BB6A", warning: "#FFB74D", danger: "#EF5350",
      radius: "0", radiusLg: "0.125rem",
      shadow: "0 2px 8px rgba(0,0,0,0.4)",
      shadowLg: "0 12px 32px -4px rgba(0,0,0,0.6), 0 0 0 1px rgba(79,195,247,0.1)",
      fontSans: fonts.sans, fontDisplay: fonts.mono, fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #0A1929 0%, #2A5580 60%, #4FC3F7 100%)",
      pattern: "linear-gradient(to right, rgba(79,195,247,0.08) 1px, transparent 1px), linear-gradient(to bottom, rgba(79,195,247,0.08) 1px, transparent 1px)",
    },
    typeScale: defaultTypeScale({ display: fonts.mono, body: fonts.sans, mono: fonts.mono, displayWeight: 600 }),
    motif: "\u2395 Blueprint",
    preview: ["#4FC3F7", "#FFB74D", "#0A1929"],
  },

  satellite: {
    id: "satellite",
    name: "Satellite",
    tagline: "Mission control, 3AM, all systems nominal",
    description: "For the person who watches SpaceX launches in their pajamas and knows what LOX tanks sound like. Deep-space navy, amber mission-control readouts, telemetry green for OK, red for anomaly. Every element looks like it's printing to a dot-matrix somewhere.",
    designer: "Dehlya Studio", year: "2026", mode: "dark",
    inspiration: "NASA Apollo mission control, JPL dashboards, SpaceX launch webcasts, amber CRT readouts, telemetry screens.",
    features: ["Deep space navy + amber telemetry", "Dot-matrix monospace feel", "Red/green status semantics", "Tight mission-control density"],
    useCases: ["Ops dashboards", "Hacker portfolios", "Monitoring tools", "Retro-tech brands"],
    tokens: {
      background: "#0B0F1A", surface: "#141827", surfaceAlt: "#1E2438", border: "#2E3450",
      text: "#E0E4F0", textMuted: "#8A93AB", textInverse: "#0B0F1A",
      primary: "#FFA726", primaryContrast: "#0B0F1A", secondary: "#66BB6A", accent: "#EF5350",
      success: "#66BB6A", warning: "#FFA726", danger: "#EF5350",
      radius: "0.125rem", radiusLg: "0.25rem",
      shadow: "0 0 0 1px rgba(255,167,38,0.08), 0 4px 12px rgba(0,0,0,0.5)",
      shadowLg: "0 16px 40px -8px rgba(0,0,0,0.7), 0 0 0 1px rgba(255,167,38,0.1)",
      fontSans: fonts.sans, fontDisplay: fonts.mono, fontMono: fonts.mono,
      gradient: "linear-gradient(135deg, #0B0F1A 0%, #1E2438 50%, #FFA726 100%)",
      pattern: "radial-gradient(rgba(255,167,38,0.08) 1px, transparent 1px)",
    },
    typeScale: defaultTypeScale({ display: fonts.mono, body: fonts.sans, mono: fonts.mono, displayWeight: 700 }),
    motif: "\u25c9 T-00:00:00",
    preview: ["#FFA726", "#66BB6A", "#0B0F1A"],
  },
}

export const themeList: ThemeDefinition[] = Object.values(themes)

export const themeIds = Object.keys(themes) as ThemeId[]
